#!/usr/bin/env bash
# tunnel_setup.sh — give this project its OWN cloudflared tunnel.
#
# Runs on the mini. Idempotent: safe to run on every deploy.
#
# WHY A SECOND TUNNEL rather than a second hostname on the trading desk's:
# that tunnel's ingress list is a file tracked in the trading-helper repo.
# Adding a hostname to it leaves that tree dirty, so the next trading deploy's
# `git pull --ff-only` refuses; and any future edit, rollback or reload of that
# file becomes a shared failure mode between two unrelated projects. A tunnel
# is free and a second cloudflared process costs a few MB. Isolation is worth
# more than that.
#
# What this does NOT do: touch ~/repo/trading-helper, its config, or its
# cloudflared process. The two tunnels share nothing but the account.
set -uo pipefail

PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NAME="${TUNNEL_NAME:-retirement}"
HOSTNAME_PUBLIC="${HOSTNAME_PUBLIC:-retirement.jbrasfield.com}"
PORT="${RETIREMENT_PORT:-8891}"
CFG="$ROOT/config/cloudflared-config.yml"

CFD="$(command -v cloudflared 2>/dev/null || true)"
[ -z "$CFD" ] && [ -x /opt/homebrew/bin/cloudflared ] && CFD=/opt/homebrew/bin/cloudflared
[ -z "$CFD" ] && [ -x /usr/local/bin/cloudflared ]    && CFD=/usr/local/bin/cloudflared
if [ -z "$CFD" ]; then
  echo "  ✗ cloudflared is not installed here:  brew install cloudflared"
  exit 1
fi
echo "  · cloudflared at $CFD"

# The account certificate. Creating a tunnel and routing DNS both need it, and
# getting one opens a browser -- so check first and say so rather than hanging
# on a prompt nobody is watching.
if [ ! -f "$HOME/.cloudflared/cert.pem" ]; then
  echo "  ✗ no ~/.cloudflared/cert.pem on this machine."
  echo "    Once, in a session on the mini (it opens a browser):"
  echo "        $CFD tunnel login"
  echo "    Then rerun the deploy. This does not affect the trading tunnel."
  exit 1
fi

# ── the tunnel ─────────────────────────────────────────────────────────────
TUNNEL_ID="$("$CFD" tunnel list --output json 2>/dev/null \
  | python3 -c "
import json,sys
try: rows = json.load(sys.stdin)
except Exception: rows = []
print(next((r['id'] for r in rows if r.get('name') == '$NAME'), ''))
" 2>/dev/null)"

if [ -z "$TUNNEL_ID" ]; then
  echo "  · creating tunnel '$NAME'"
  "$CFD" tunnel create "$NAME" >/dev/null 2>&1 || {
    echo "  ✗ could not create the tunnel"; exit 1; }
  TUNNEL_ID="$("$CFD" tunnel list --output json 2>/dev/null \
    | python3 -c "
import json,sys
print(next((r['id'] for r in json.load(sys.stdin) if r.get('name') == '$NAME'), ''))
" 2>/dev/null)"
  [ -n "$TUNNEL_ID" ] || { echo "  ✗ created it but cannot find its id"; exit 1; }
  echo "  ✓ tunnel '$NAME' created"
else
  echo "  ✓ tunnel '$NAME' already exists"
fi
echo "  · id $TUNNEL_ID"

CREDS="$HOME/.cloudflared/$TUNNEL_ID.json"
[ -f "$CREDS" ] || { echo "  ✗ no credentials file at $CREDS"; exit 1; }

# ── its own config, in THIS repo ───────────────────────────────────────────
mkdir -p "$ROOT/config"
cat > "$CFG" <<YML
# Generated by scripts/tunnel_setup.sh — this project's own tunnel.
# Deliberately separate from trading-helper's: nothing here can break that one.
tunnel: $TUNNEL_ID
credentials-file: $CREDS

ingress:
  - hostname: $HOSTNAME_PUBLIC
    service: http://localhost:$PORT

  - service: http_status:404
YML
echo "  ✓ wrote $CFG"

"$CFD" --config "$CFG" tunnel ingress validate >/dev/null 2>&1 \
  && echo "  ✓ config validates" \
  || { echo "  ✗ config does not validate"; exit 1; }

# ── DNS ────────────────────────────────────────────────────────────────────
ROUTE_OUT="$("$CFD" tunnel route dns "$NAME" "$HOSTNAME_PUBLIC" 2>&1)"; RC=$?
if [ "$RC" = 0 ]; then
  echo "  ✓ DNS route created for $HOSTNAME_PUBLIC"
elif printf '%s' "$ROUTE_OUT" | grep -qi 'already\|exists\|duplicate'; then
  echo "  ✓ DNS route already in place"
else
  echo "  ✗ could not route DNS:"
  printf '      %s\n' "$ROUTE_OUT" | head -3
  echo "    If that record points at another tunnel, delete it in the Cloudflare"
  echo "    dashboard and rerun — it must CNAME to $TUNNEL_ID.cfargotunnel.com"
  exit 1
fi

echo "  · trading-helper untouched"
